### ISSUE TITLE
horoscop tutorial

### ISSUE THREAD

**Issue by drxos** [mskala/horoscop#1]
## Hello

I like you latex package. Unfortunetly, I can turn it correctly. So via the present, I want you to show use an complete example tex file using horoscop.

Thanks.

**Comment by mskala** [comment]
Here's a working example:
```
\documentclass{article}
\usepackage{horoscop}
\begin{document}
\horocalcparms{1976}{8}{1}{17:22:19}{W123:20:38}{N48:25:53}
\horocalculate
\begin{horoscope}
  \horowheelVancouver
\end{horoscope}
\end{document}
```

Compile it with `pdflatex -shell-escape` and the filename.  It requires that Swiss Ephemeris be installed in such a way that PDFLaTeX can run it.  For more information, I strongly suggest reading the horoscop manual.

**Comment by drxos** [comment]
Okay.

**Comment by janegca** [comment]
Hi...tried out your example, but get this error:
[Loading MPS to PDF converter (version 2006.09.02).]
)
! Missing \endcsname inserted.
<to be read again> 
                   \par 
l.5 \horocalculate

swetest is installed correctly. 

When I try the manual entry example as given in the horoscop pdf, I get this error:

[Loading MPS to PDF converter (version 2006.09.02).]
)
! Missing number, treated as zero.
<to be read again> 
                   \horoCuspVIIPos 
l.36 \end
         {horoscope}
? 

Any ideas on what may be causing the problems?
Many thanks

**Comment by mskala** [comment]
There's an error in the manual regarding entry of manual coordinates.  All the macros should have "Pos" in the names, so each line like "\def\horoCuspI{207.9120843}" should read "\def\horoCuspIPos{207.9120843}" .  Try changing that and see if it makes a difference, for that example.  It's on my TODO list to push a new release with this documentation problem fixed, very soon.

That doesn't address the "Missing \endcsname inserted" issue with the other example.  My first thought is that you may be having issues with LaTeX's ability to run swetest.  Make sure the location of swetest is in the PATH, and that you are running LaTeX with shell escapes turned on.  There may be more information in the log file, if you check that.

**Comment by mskala** [comment]
Please note that Github issues are not a good way to ask for support on this package.  Email to mskala@ansuz.sooke.bc.ca is preferable.  The version in Github may not be up to date, either, and may not be updated in the future.  I recommend getting this package from CTAN instead.

**Comment by janegca** [comment]
Just an update in case anyone else has a similar problem:
(1) Make sure you unpack all the sweph ephemeris files and that both they and swetest.exe are in your path
(2) The example for creating files manually is missing the 'Pos' ending on the house cusp values. The manual's example chart corrected positions are:

\def\horoSunPos{267.5002492}\def\horoSunVel{1.0185515}
\def\horoMoonPos{229.2067659}\def\horoMoonVel{11.9237313}
\def\horoMercuryPos{249.2355412}\def\horoMercuryVel{1.4004420}
\def\horoVenusPos{229.6610785}\def\horoVenusVel{0.4165367}
\def\horoMarsPos{271.9242409}\def\horoMarsVel{0.7571908}
\def\horoJupiterPos{228.1368358}\def\horoJupiterVel{0.1927896}
\def\horoSaturnPos{128.1056809}\def\horoSaturnVel{-0.0516070}
\def\horoUranusPos{79.4428694}\def\horoUranusVel{-0.0421386}
\def\horoNeptunePos{190.6482218}\def\horoNeptuneVel{0.0133648}
\def\horoPlutoPos{133.0955746}\def\horoPlutoVel{-0.0150157}
\def\horoNorthNodePos{70.7814892}\def\horoNorthNodeVel{-0.0529425}
\def\horoLilithPos{265.3475147}\def\horoLilithVel{0.1108368}
\def\horoCuspIPos{207.9120843}
\def\horoCuspIIPos{236.5553269}
\def\horoCuspIIIPos{267.6976404}
\def\horoCuspIVPos{300.5365877}
\def\horoCuspVPos{332.9973490}
\def\horoCuspVIPos{2.5292853}
\def\horoCuspVIIPos{27.9120843}
\def\horoCuspVIIIPos{56.5553269}
\def\horoCuspIXPos{87.6976404}
\def\horoCuspXPos{120.5365877}
\def\horoCuspXIPos{152.9973490}
\def\horoCuspXIIPos{182.5292853}

Many thanks to Matthew for helping me clear up the problem so swiftly and for creating the package in the first place.
